version: "3"
services:
  site:
    build: 
      context: .
      args:
        bulma_version: ${BULMA_VERSION:-0.9.4}
    image: mysite:latest
    container_name: mysite
    expose:
      - "8043"
    labels:
      - traefik.enable=true
      - traefik.http.routers.mysite.rule=Host(`dev.local`)
      - traefik.http.services.mysite.loadbalancer.server.port=8043
  proxy:
    image: docker.io/traefik:latest
    container_name: traefik
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    restart: unless-stopped